version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/aquacharge # mounts local code for live reload
    ports:
      - "5050:5050"
    environment:
      - FLASK_ENV=development

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/usr/src/app  # mounts local code for hot reload
      - /usr/src/app/node_modules
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://backend:5050
    depends_on:
      - backend